class ActivityType():
    ACTIVE = "ACTIVE"
    ALL = "ALL"
class metricsFilesType():
    INITIAL = "INITIAL"
    CURRENT = "CURRENT"
class BoolType():
    YES = "YES"
    NO = "NO"
class ReqMethod():
    """Request Method"""
    POST = "post"
    GET = "get"

class LQAType():
    """LQAType"""
    LANGUAGE = "LANGUAGE"
    FILE = "FILE"

class FilesScopeType():
    """FilesScopeType"""
    JOB = "JOB"
    PROJECT = "PROJECT"

class FetchTargetFileType():
    """FetchTargetFileType"""
    NO_CONTENT = "NO_CONTENT"
    NON_ANALYSABLE = "NON_ANALYSABLE"
    NOT_SUPPORTED = "NOT_SUPPORTED"

class FileNameFilterType():
    """FileNameFilterType"""
    CONTAINS = "CONTAINS"
    EQUALS = "EQUALS"
    STARTS_WITH = "STARTS_WITH"
    ENDS_WITH = "ENDS_WITH"

class FileType():
    """FileType"""
    TARGET = "TARGET"
    XLIFF = "XLIFF"
    XLIFF_NTP = "XLIFF_NTP"
    QA_REPORT = "QA_REPORT"
    HTML = "HTML"
    HTML_TABLE = "HTML_TABLE"
    PDF = "PDF"
    PDF_TABLE = "PDF_TABLE"
    TIPP = "TIPP"
    HTML_EXTENDED_TABLE = "HTML_EXTENDED_TABLE"
    HTML_COLOURED = "HTML_COLOURED"
    HTML_COLOURED_BY_MATCH_RATE = "HTML_COLOURED_BY_MATCH_RATE"
    PDF_EXTENDED_TABLE = "PDF_EXTENDED_TABLE"
    PDF_COLOURED = "PDF_COLOURED"
    PDF_COLOURED_BY_XLIFF_DOC_STATUS = "PDF_COLOURED_BY_XLIFF_DOC_STATUS"
    PDF_COLOURED_BY_MATCH_RATE = "PDF_COLOURED_BY_MATCH_RATE"
    TARGET_COLOURED_BY_MATCH_RATE = "TARGET_COLOURED_BY_MATCH_RATE"
    TARGET_COLOURED_BY_XLIFF_DOC_STATUS = "TARGET_COLOURED_BY_XLIFF_DOC_STATUS"
    XLIFF_DOC = "XLIFF_DOC"
    LQA_REPORT = "LQA_REPORT"
    LQA_EXTENDED_TABLE_REPORT = "LQA_EXTENDED_TABLE_REPORT"
    TARGET_PSEUDO = "TARGET_PSEUDO"
    MULTI_EXCEL = "MULTI_EXCEL"
    EXCEL_EXTENDED_TABLE = "EXCEL_EXTENDED_TABLE"
